version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    # 端口映射 本机端口:docker 端口
    ports:
      - "80:80"
      - "443:443"
    # 文件挂载  本地目录: docker 目录 后面的 ro 设置为只读
    volumes:
      # 配置文件
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./nginx/conf/expires.conf:/etc/nginx/expires.conf:ro
      # ssl 证书目录
      # - ./nginx/conf/ssl:/etc/nginx/ssl:ro
      # 虚拟主机目录
      - ./nginx/conf/vhost.d:/etc/nginx/vhost.d:ro
      # 默认首页目录
      - ./nginx/html:/etc/nginx/html:ro
      # log root
      - ./nginx/log:/var/log/nginx
      # www root
      - ./www:/var/www/
    depends_on:
      - php
  php:
    build: ./php
    restart: always
    volumes:
      # 配置目录
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      # crontab
      - ./php/crontab/crontab:/etc/cron.d/cron
      # log root
      - ./php/log:/var/log/php
      # www root
      - ./www:/var/www/
    command:
      - /bin/sh
      - -c
      - |
        php -v
        chmod 0644 /etc/cron.d/cron
        crontab /etc/cron.d/cron
        cron
        php-fpm
