version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    # 端口映射 本机端口:docker 端口
    ports:
      - "80:80"
      - "443:443"
    # 文件挂载  本地目录: docker 目录 后面的 ro 设置为只读
    volumes:
      # 配置文件
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./nginx/conf/expires.conf:/etc/nginx/expires.conf:ro
      # ssl 证书目录
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # 虚拟主机目录
      - ./nginx/conf/vhost.d:/etc/nginx/vhost.d:ro
      # 默认首页目录
      - ./nginx/html:/etc/nginx/html:ro
      # log root
      - ./nginx/log:/var/log/nginx
      # www root
      - ./www:/var/www/
    depends_on:
      - php
    networks:
      mynet:
        ipv4_address: 172.28.12.3
  php:
    build: ./php
    restart: always
    volumes:
      # 配置目录
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d:rw
      # crontab
      - ./php/crontab/crontab:/etc/cron.d/cron
      # log root
      - ./php/log:/var/log/php:rw
      # www root
      - ./www:/var/www/:rw
    depends_on:
      - mysql
      - redis
    networks:
      mynet:
        ipv4_address: 172.28.12.4
    extra_hosts:
      - "movielaravel.test:172.28.12.3"
  mysql:
    build: 
      context: ./mysql
      args:
        ver: ${MYSQL_VERSION}
    ports:
      - "33060:3306"
    restart: always
    volumes:
      - ${DATA_PATH}/mysql/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: crazyhl
      MYSQL_PASSWORD: 123456789
    networks:
      mynet:
        ipv4_address: 172.28.12.5
  redis:
    build: ./redis
    restart: always
    volumes:
      - ${DATA_PATH}/redis/data/:/data
    networks:
      mynet:
        ipv4_address: 172.28.12.6
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      mynet:
        ipv4_address: 172.28.12.10
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8088:80"
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.12.0/24
            