version: '3'
services:
  web:
    # 基础镜像
    image: "nginx:latest"
    # 端口映射 本机端口:docker 端口
    ports:
     - "80:80"
    # 文件挂载  本地目录: docker 目录 后面的 ro 设置为只读
    volumes:
     #配置目录
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     #默认首页目录
     - ./nginx/html:/etc/nginx/html:ro
     #默认日志目录
     - ./nginx/log:/var/log/nginx:cached
     # 项目路径
     - ./code:/var/www/:cached
    depends_on:
      - php
    restart: always
  php:
    build: ./php
    restart: always
    volumes:
      # 项目路径
      - ./code:/var/www/:cached
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
  #   depends_on:
  #     - mysql
  # mysql:
  #   image: "mysql:5"
  #   ports:
  #     - "33060:3306"
  #   restart: always
  #   volumes:
  #     - $PWD/db/data/:/var/lib/mysql:cached
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456789
  #     MYSQL_USER: crazyhl
  #     MYSQL_PASSWORD: 123456789
